### ISSUE TITLE
หัวข้อโปรเจ็ค

### ISSUE THREAD

**Issue by SCKagura** [SCKagura/Com_Prog_Project_2.0#1]
เสนอหัวข้อโปรเจ็ค 
-scope ของโปรเจ็ค
ทำแบบไหน มีอะไรบ้าง

**Comment by Phurinon** [comment]
เป็นแนวฝึกคำศัพท์ภาษาอังกฤษ
มีคำศัพท์ให้จำความหมายทีละคำๆ
สามารถดูคำต่อไปหรือด้านหน้าได้
จะฝึกทีละ 10 คำ แล้วทดสอบให้เขียนความหมายของ
แต่ละคำ หากผ่านจะจำชุดต่อไป ถ้าไม่ผ่านก็กลับไปจำ
ใหม่ ขอบเขตอาจจะเริ่มที่ 50-100 คำศัพท์ก่อน
