### ISSUE TITLE
Code แยกฟังก์ชันต่างๆ

### ISSUE THREAD

**Issue by SCKagura** [SCKagura/Com_Prog_Project_2.0#3]

**Comment by SCKagura** [comment]
![int main](https://user-images.githubusercontent.com/110963025/225813760-aee2ac69-2668-4adb-9d18-8a3608f104cd.png)

**Comment by Phurinon** [comment]
![D266131C-E95B-4CDA-B6E7-BBF8CAF66FAE](https://user-images.githubusercontent.com/110959150/225814608-de440a61-3dc5-49aa-9d17-d201b8aba57e.jpeg)

Function Gameresult

**Comment by RATCHANON2099** [comment]
Function display_random_question 
![FD858091-0937-45B2-88A7-5D6E35EF4797](https://user-images.githubusercontent.com/110969818/225816062-a6e98bbf-c52c-439d-9457-10e79261a347.png)

**Comment by pornchanokppp** [comment]
![Uploading 74FAC47A-7C64-45C2-9559-A6A6119AA4BB.png…]()

**Comment by pornchanokppp** [comment]
![B74687AE-105E-4BB3-BC58-AA10A16430AA](https://user-images.githubusercontent.com/110967897/225826033-2d2049ba-edbb-4446-bafb-3eb239157982.png)
